FINANCIAL_GROUPS_Q = {
        "Revenue & Profitability": [
            "Revenue", "Gross Profit",
            "Operating Income", "Net Income",
        ],
        "QoQ Revenue & Profitability": [
            "Revenue QoQ", "Gross Profit QoQ",
            "Operating Income QoQ","Net Income QoQ"
        ],
        "Cash Flow": [
            "Operating Cash Flow",
            "Capital Expenditure", "Free Cash Flow"
        ],
        "QoQ Cash Flow": [
            "Operating Cash Flow QoQ",
            "Free Cash Flow QoQ"
        ],
        "Balance Sheet Overview": [
            "Total Assets", "Total Liabilities", "Equity"
        ],
        "Working Capital Components": [
            "Current Assets", "Current Liabilities", "Inventory", "Cash", "Receivables"
        ],
        "Efficiency Inputs": [
            "Invested Capital", "Retained Earnings", "EBIT", "EBIT QoQ"
        ],
        "EBIT QoQ": [
            "EBIT QoQ"
        ],
        "Working Capital Derived": [
            "Working Capital"
        ]
}

FINANCIAL_METRIC_EXPLANATIONS_Q = {
        "Revenue": {
            "formal": "**Revenue** is the total amount of income generated from normal business operations.",
            "casual": "It's the top line — how much money the company made before any costs.",
            "latex": None,
            "guide": "- Higher revenue usually signals business growth.\n- Compare over time and across competitors."
        },
        "Revenue QoQ": {
            "formal": "**Revenue QoQ** shows the percentage growth or decline in revenue compared to the previous quarter.",
            "casual": "Did they sell more stuff than last quarter? That's what this shows.",
            "latex": r"\text{Revenue QoQ} = \left(\frac{R_t - R_{t-1}}{R_{t-1}}\right) \times 100",
            "guide": "- Above 5% = solid growth.\n- Negative = shrinking — investigate why."
        },
        "Gross Profit": {
            "formal": "**Gross Profit** is Revenue minus Cost of Goods Sold (COGS).",
            "casual": "What’s left after making the product but before paying the bills.",
            "latex": r"\text{Gross Profit} = \text{Revenue} - \text{COGS}",
            "guide": "- Consistent growth is a positive sign.\n- Volatility may indicate pricing or cost issues."
        },
        "Gross Profit QoQ": {
            "formal": "**Gross Profit QoQ** shows quarter-over-quarter growth in gross profit.",
            "casual": "Is the raw profit chunk growing each quarter? This answers that.",
            "latex": r"\text{Gross Profit QoQ} = \left(\frac{GP_t - GP_{t-1}}{GP_{t-1}}\right) \times 100",
            "guide": "- Look for steady or improving trends.\n- Sudden dips may signal cost issues."
        },
        "Operating Income": {
            "formal": "**Operating Income** is earnings before interest and taxes (EBIT).",
            "casual": "Profit from actual operations, before the accountants get fancy.",
            "latex": r"\text{Operating Income} = \text{Gross Profit} - \text{Operating Expenses}",
            "guide": "- Healthy operating income means the core business is profitable."
        },
        "Operating Income QoQ": {
            "formal": "**Operating Income QoQ** shows the growth in operating income over quarters.",
            "casual": "Are operations getting more efficient or just lucky?",
            "latex": r"\text{OI QoQ} = \left(\frac{OI_t - OI_{t-1}}{OI_{t-1}}\right) \times 100",
            "guide": "- Consistent growth is very bullish.\n- Sharp drops may be red flags."
        },
        "Net Income": {
            "formal": "**Net Income** is total profit after all expenses, taxes, and costs.",
            "casual": "The bottom line. What the company *actually* keeps.",
            "latex": r"\text{Net Income} = \text{Revenue} - \text{Total Expenses}",
            "guide": "- A must-watch metric for investors.\n- Negative = company lost money."
        },
        "Net Income QoQ": {
            "formal": "**Net Income QoQ** shows percentage change in net income from previous quarter.",
            "casual": "Is the final profit moving in the right direction?",
            "latex": r"\text{Net Income QoQ} = \left(\frac{NI_t - NI_{t-1}}{NI_{t-1}}\right) \times 100",
            "guide": "- Positive trend = company’s becoming more profitable.\n- Volatility can be risky."
        },
        "Operating Cash Flow": {
            "formal": "**Operating Cash Flow (OCF)** is cash generated by core business activities.",
            "casual": "Cash coming in from day-to-day operations — not investments or loans.",
            "latex": None,
            "guide": "- Positive OCF shows the business can sustain itself.\n- Negative OCF is a warning sign."
        },
        "Operating Cash Flow QoQ": {
            "formal": "**OCF QoQ** shows the quarterly growth of operating cash flow.",
            "casual": "Are they bringing in more real money from business? That’s the check.",
            "latex": r"\text{OCF QoQ} = \left(\frac{OCF_t - OCF_{t-1}}{OCF_{t-1}}\right) \times 100",
            "guide": "- Growth means strong operational efficiency.\n- Decline = dig into why."
        },
        "Capital Expenditure": {
            "formal": "**Capital Expenditure (CapEx)** refers to funds used to acquire or upgrade assets.",
            "casual": "Big spending on buildings, equipment, or new tech.",
            "latex": None,
            "guide": "- High CapEx can mean growth plans.\n- But too much = watch cash burn."
        },
        "Free Cash Flow": {
            "formal": "**Free Cash Flow (FCF)** is the cash left after CapEx — it shows real financial strength.",
            "casual": "What’s left to invest, repay debt, or reward shareholders.",
            "latex": r"\text{FCF} = \text{Operating Cash Flow} - \text{CapEx}",
            "guide": "- Positive FCF is ideal.\n- Negative FCF could mean expansion or trouble."
        },
        "Free Cash Flow QoQ": {
            "formal": "**FCF QoQ** shows growth of Free Cash Flow across quarters.",
            "casual": "Is the leftover money growing or drying up?",
            "latex": r"\text{FCF QoQ} = \left(\frac{FCF_t - FCF_{t-1}}{FCF_{t-1}}\right) \times 100",
            "guide": "- Growth = more flexibility.\n- Decline = check cash burn reasons."
        },
        "Total Assets": {
            "formal": "**Total Assets** are everything the company owns — cash, buildings, inventory, etc.",
            "casual": "The entire pile of stuff the business owns.",
            "latex": r"\text{Assets} = \text{Liabilities} + \text{Equity}",
            "guide": "- Bigger assets can mean more power.\n- Look at asset quality, not just size."
        },
        "Total Liabilities": {
            "formal": "**Total Liabilities** represent all financial debts and obligations.",
            "casual": "What the company owes — loans, bills, etc.",
            "latex": None,
            "guide": "- Watch rising liabilities.\n- Compare to assets and equity."
        },
        "Equity": {
            "formal": "**Equity** is the residual value of assets after deducting liabilities.",
            "casual": "What’s left for shareholders after paying off debts.",
            "latex": r"\text{Equity} = \text{Assets} - \text{Liabilities}",
            "guide": "- Positive equity = good.\n- Negative = serious trouble."
        },
        "Current Assets": {
            "formal": "**Current Assets** are assets expected to be converted to cash within a year.",
            "casual": "Short-term stuff: cash, inventory, receivables.",
            "latex": None,
            "guide": "- High current assets = strong short-term position."
        },
        "Current Liabilities": {
            "formal": "**Current Liabilities** are obligations due within one year.",
            "casual": "Bills and debts due soon.",
            "latex": None,
            "guide": "- Compare with current assets to assess liquidity."
        },
        "Inventory": {
            "formal": "**Inventory** includes raw materials, work-in-progress, and finished goods.",
            "casual": "Stuff sitting in the warehouse, ready to sell.",
            "latex": None,
            "guide": "- Rising inventory with flat sales = warning.\n- Compare to revenue."
        },
        "Cash": {
            "formal": "**Cash** is liquid money the company holds.",
            "casual": "Money ready to use — no strings attached.",
            "latex": None,
            "guide": "- Higher cash = safety buffer.\n- Too much idle cash? Could be better used."
        },
        "Receivables": {
            "formal": "**Receivables** are amounts owed to the company by customers.",
            "casual": "Unpaid customer bills — money they’re still waiting on.",
            "latex": None,
            "guide": "- Rising receivables = strong sales OR poor collections."
        },
        "Invested Capital": {
            "formal": "**Invested Capital** is the total capital invested by shareholders and lenders.",
            "casual": "All the money put into running the business.",
            "latex": r"\text{Invested Capital} = \text{Equity} + \text{Debt} - \text{Cash}",
            "guide": "- Used in ROIC calculations.\n- Efficiency of this capital matters."
        },
        "Retained Earnings": {
            "formal": "**Retained Earnings** are profits reinvested into the company, not paid as dividends.",
            "casual": "Past profits the company kept instead of sharing.",
            "latex": None,
            "guide": "- Growth means profit reinvestment.\n- Too much = maybe no better use found."
        },
        "EBIT": {
            "formal": "**EBIT (Earnings Before Interest & Taxes)** is core profit from operations.",
            "casual": "The profit before banks or taxmen get involved.",
            "latex": r"\text{EBIT} = \text{Revenue} - \text{COGS} - \text{Operating Expenses}",
            "guide": "- Used in valuation and efficiency ratios.\n- Excludes tax & interest noise."
        },
        "EBIT QoQ": {
            "formal": "**EBIT QoQ** shows quarter-over-quarter growth in EBIT.",
            "casual": "Is the operating engine becoming more profitable?",
            "latex": r"\text{EBIT QoQ} = \left(\frac{EBIT_t - EBIT_{t-1}}{EBIT_{t-1}}\right) \times 100",
            "guide": "- Strong signal of operational strength if rising consistently."
        },
        "Working Capital": {
            "formal": "**Working Capital** is Current Assets minus Current Liabilities.",
            "casual": "Money left to run day-to-day operations.",
            "latex": r"\text{Working Capital} = \text{Current Assets} - \text{Current Liabilities}",
            "guide": "- Positive = healthy liquidity.\n- Negative = short-term trouble risk."
        }
}

FINANCIAL_GROUPS_Y = {
        "Revenue & Profitability": [
            "Revenue", "Gross Profit",
            "Operating Income", "Net Income",
        ],
        "QoQ Revenue & Profitability": [
            "Revenue YoY", "Gross Profit YoY",
            "Operating Income YoY","Net Income YoY"
        ],
        "Cash Flow": [
            "Operating Cash Flow",
            "Capital Expenditure", "Free Cash Flow"
        ],
        "YoY Cash Flow": [
            "Operating Cash Flow YoY",
            "Free Cash Flow YoY"
        ],
        "Balance Sheet Overview": [
            "Total Assets", "Total Liabilities", "Equity"
        ],
        "Working Capital Components": [
            "Current Assets", "Current Liabilities", "Inventory", "Cash", "Receivables"
        ],
        "Efficiency Inputs": [
            "Invested Capital", "Retained Earnings", "EBIT"
        ],
        "EBIT YoY": [
            "EBIT YoY"
        ],
        "Working Capital Derived": [
            "Working Capital"
        ]
    }

FINANCIAL_METRIC_EXPLANATIONS_Y = {
        "Revenue": {
            "formal": "**Revenue** is the total amount of income generated from normal business operations.",
            "casual": "It's the top line — how much money the company made before any costs.",
            "latex": None,
            "guide": "- Higher revenue usually signals business growth.\n- Compare over time and across competitors."
        },
        "Revenue YoY": {
            "formal": "**Revenue YoY** shows the percentage growth or decline in revenue compared to the previous year.",
            "casual": "Did they sell more stuff than last year? That's what this shows.",
            "latex": r"\text{Revenue QoQ} = \left(\frac{R_t - R_{t-1}}{R_{t-1}}\right) \times 100",
            "guide": "- Above 5% = solid growth.\n- Negative = shrinking — investigate why."
        },
        "Gross Profit": {
            "formal": "**Gross Profit** is Revenue minus Cost of Goods Sold (COGS).",
            "casual": "What’s left after making the product but before paying the bills.",
            "latex": r"\text{Gross Profit} = \text{Revenue} - \text{COGS}",
            "guide": "- Consistent growth is a positive sign.\n- Volatility may indicate pricing or cost issues."
        },
        "Gross Profit YoY": {
            "formal": "**Gross Profit YoY** shows year-over-year growth in gross profit.",
            "casual": "Is the raw profit chunk growing each year? This answers that.",
            "latex": r"\text{Gross Profit YoY} = \left(\frac{GP_t - GP_{t-1}}{GP_{t-1}}\right) \times 100",
            "guide": "- Look for steady or improving trends.\n- Sudden dips may signal cost issues."
        },
        "Operating Income": {
            "formal": "**Operating Income** is earnings before interest and taxes (EBIT).",
            "casual": "Profit from actual operations, before the accountants get fancy.",
            "latex": r"\text{Operating Income} = \text{Gross Profit} - \text{Operating Expenses}",
            "guide": "- Healthy operating income means the core business is profitable."
        },
        "Operating Income YoY": {
            "formal": "**Operating Income YoY** shows the growth in operating income over years.",
            "casual": "Are operations getting more efficient or just lucky?",
            "latex": r"\text{OI YoY} = \left(\frac{OI_t - OI_{t-1}}{OI_{t-1}}\right) \times 100",
            "guide": "- Consistent growth is very bullish.\n- Sharp drops may be red flags."
        },
        "Net Income": {
            "formal": "**Net Income** is total profit after all expenses, taxes, and costs.",
            "casual": "The bottom line. What the company *actually* keeps.",
            "latex": r"\text{Net Income} = \text{Revenue} - \text{Total Expenses}",
            "guide": "- A must-watch metric for investors.\n- Negative = company lost money."
        },
        "Net Income YoY": {
            "formal": "**Net Income YoY** shows percentage change in net income from previous year.",
            "casual": "Is the final profit moving in the right direction?",
            "latex": r"\text{Net Income YoY} = \left(\frac{NI_t - NI_{t-1}}{NI_{t-1}}\right) \times 100",
            "guide": "- Positive trend = company's becoming more profitable.\n- Volatility can be risky."
        },
        "Operating Cash Flow": {
            "formal": "**Operating Cash Flow (OCF)** is cash generated by core business activities.",
            "casual": "Cash coming in from day-to-day operations — not investments or loans.",
            "latex": None,
            "guide": "- Positive OCF shows the business can sustain itself.\n- Negative OCF is a warning sign."
        },
        "Operating Cash Flow YoY": {
            "formal": "**OCF YoY** shows the yearly growth of operating cash flow.",
            "casual": "Are they bringing in more real money from business? That's the check.",
            "latex": r"\text{OCF YoY} = \left(\frac{OCF_t - OCF_{t-1}}{OCF_{t-1}}\right) \times 100",
            "guide": "- Growth means strong operational efficiency.\n- Decline = dig into why."
        },
        "Capital Expenditure": {
            "formal": "**Capital Expenditure (CapEx)** refers to funds used to acquire or upgrade assets.",
            "casual": "Big spending on buildings, equipment, or new tech.",
            "latex": None,
            "guide": "- High CapEx can mean growth plans.\n- But too much = watch cash burn."
        },
        "Free Cash Flow": {
            "formal": "**Free Cash Flow (FCF)** is the cash left after CapEx — it shows real financial strength.",
            "casual": "What's left to invest, repay debt, or reward shareholders.",
            "latex": r"\text{FCF} = \text{Operating Cash Flow} - \text{CapEx}",
            "guide": "- Positive FCF is ideal.\n- Negative FCF could mean expansion or trouble."
        },
        "Free Cash Flow YoY": {
            "formal": "**FCF YoY** shows growth of Free Cash Flow across years.",
            "casual": "Is the leftover money growing or drying up?",
            "latex": r"\text{FCF YoY} = \left(\frac{FCF_t - FCF_{t-1}}{FCF_{t-1}}\right) \times 100",
            "guide": "- Growth = more flexibility.\n- Decline = check cash burn reasons."
        },
        "Total Assets": {
            "formal": "**Total Assets** are everything the company owns — cash, buildings, inventory, etc.",
            "casual": "The entire pile of stuff the business owns.",
            "latex": r"\text{Assets} = \text{Liabilities} + \text{Equity}",
            "guide": "- Bigger assets can mean more power.\n- Look at asset quality, not just size."
        },
        "Total Liabilities": {
            "formal": "**Total Liabilities** represent all financial debts and obligations.",
            "casual": "What the company owes — loans, bills, etc.",
            "latex": None,
            "guide": "- Watch rising liabilities.\n- Compare to assets and equity."
        },
        "Equity": {
            "formal": "**Equity** is the residual value of assets after deducting liabilities.",
            "casual": "What’s left for shareholders after paying off debts.",
            "latex": r"\text{Equity} = \text{Assets} - \text{Liabilities}",
            "guide": "- Positive equity = good.\n- Negative = serious trouble."
        },
        "Current Assets": {
            "formal": "**Current Assets** are assets expected to be converted to cash within a year.",
            "casual": "Short-term stuff: cash, inventory, receivables.",
            "latex": None,
            "guide": "- High current assets = strong short-term position."
        },
        "Current Liabilities": {
            "formal": "**Current Liabilities** are obligations due within one year.",
            "casual": "Bills and debts due soon.",
            "latex": None,
            "guide": "- Compare with current assets to assess liquidity."
        },
        "Inventory": {
            "formal": "**Inventory** includes raw materials, work-in-progress, and finished goods.",
            "casual": "Stuff sitting in the warehouse, ready to sell.",
            "latex": None,
            "guide": "- Rising inventory with flat sales = warning.\n- Compare to revenue."
        },
        "Cash": {
            "formal": "**Cash** is liquid money the company holds.",
            "casual": "Money ready to use — no strings attached.",
            "latex": None,
            "guide": "- Higher cash = safety buffer.\n- Too much idle cash? Could be better used."
        },
        "Receivables": {
            "formal": "**Receivables** are amounts owed to the company by customers.",
            "casual": "Unpaid customer bills — money they’re still waiting on.",
            "latex": None,
            "guide": "- Rising receivables = strong sales OR poor collections."
        },
        "Invested Capital": {
            "formal": "**Invested Capital** is the total capital invested by shareholders and lenders.",
            "casual": "All the money put into running the business.",
            "latex": r"\text{Invested Capital} = \text{Equity} + \text{Debt} - \text{Cash}",
            "guide": "- Used in ROIC calculations.\n- Efficiency of this capital matters."
        },
        "Retained Earnings": {
            "formal": "**Retained Earnings** are profits reinvested into the company, not paid as dividends.",
            "casual": "Past profits the company kept instead of sharing.",
            "latex": None,
            "guide": "- Growth means profit reinvestment.\n- Too much = maybe no better use found."
        },
        "EBIT": {
            "formal": "**EBIT (Earnings Before Interest & Taxes)** is core profit from operations.",
            "casual": "The profit before banks or taxmen get involved.",
            "latex": r"\text{EBIT} = \text{Revenue} - \text{COGS} - \text{Operating Expenses}",
            "guide": "- Used in valuation and efficiency ratios.\n- Excludes tax & interest noise."
        },
        "EBIT YoY": {
            "formal": "**EBIT YoY** shows quarter-over-quarter growth in EBIT.",
            "casual": "Is the operating engine becoming more profitable?",
            "latex": r"\text{EBIT YoY} = \left(\frac{EBIT_t - EBIT_{t-1}}{EBIT_{t-1}}\right) \times 100",
            "guide": "- Strong signal of operational strength if rising consistently."
        },
        "Working Capital": {
            "formal": "**Working Capital** is Current Assets minus Current Liabilities.",
            "casual": "Money left to run day-to-day operations.",
            "latex": r"\text{Working Capital} = \text{Current Assets} - \text{Current Liabilities}",
            "guide": "- Positive = healthy liquidity.\n- Negative = short-term trouble risk."
        }
    }

HEADER_METRIC = {
    'Current Price' : {
        'formal': "**Current Price** is the latest trading price of the stock on the exchange.",
        "casual":"It's the price someone's willing to pay for the stock right now.",
        "latex":None,
        "guide":"This value is not that useful by itself — compare it with EPS, Book Value, or peers to judge whether it's high or low."
    },
    'Book Value' : {
        'formal': "**Book Value** is the total value of the company's assets minus liabilities, per share.",
        "casual":"Think of it as what's left if the company sold everything and paid off all the bills.",
        "latex":r"\text{Book Value} = \frac{\text{Assets} - \text{Liabilities}}{\text{Outstanding Shares}}",
        "guide":"If the stock price is below the book value, it could be undervalued — or in trouble. Use with caution and comparison."
    },
    'Market Cap' : {
        'formal': "**Market Capitalization** is the total market value of a company's outstanding shares.",
        "casual":"It's how much the market thinks the company is worth — or how expensive it is to buy the whole thing.",
        "latex":r"\text{Market Cap} = \text{Share Price} \times \text{Total Shares}",
        "guide":"- Less than $2B → Small-cap (riskier, high growth potential)\n - Between $2B-$10B → Mid-cap (balanced)\n - Greater than $10B → Large-cap (stable, less risky)\n\n **May be different in you country or exchange so verify**"
    },
    '52-Week Low' : {
        'formal':"**52-Week Low** is the lowest price the stock traded at in the past year.",
        "casual":"The stock was this sad at some point last year — drama!",
        "latex":None,
        "guide":"If current price is near this, the stock might be undervalued (or struggling). Good for bargain hunters — Proceed with caution."
    },
    "52-Week High" : {
        'formal':"**52-Week High** is the highest price the stock traded at in the past year.",
        "casual":"This is the stock’s bragging moment — peak flex mode.",
        "latex":None,
        "guide":"If the current price is near this, the stock might be overbought — or performing exceptionally well."
    },
    'Avg Volume (10D)' : {
        'formal':"**Average Volume (10D)** is the average number of shares traded daily over the last 10 days.",
        "casual": "Basically, how much people have been buying/selling it lately.",
        "latex":None,
        "guide":"Higher volume = more liquidity and interest.\nSudden volume spikes often signal big news or sentiment changes."
    },
    "Dividend Yield": {
        'formal':"**Dividend Yield** shows the return from dividends relative to the stock price.",
        "casual":"How much the company pays you back for holding its shares. Kind of like cashback but fancier.",
        "latex":r"\text{Dividend Yield} = \left( \frac{\text{Annual Dividend}}{\text{Price}} \right) \times 100",
        "guide":"- Greater Than 5% → High yield (check sustainability)\n - Between 2%–5% → Healthy for stable companies\n - Less than 2% → Low, common for growth stocks"
    },
    'PE Ratio' : {
        'formal':"**P/E Ratio** compares the stock price to its earnings per share (EPS).",
        "casual":"How expensive the stock is based on how much it earns. High P/E = You're expecting future growth — or maybe just speculating..",
        "latex":r"\text{P/E Ratio} = \frac{\text{Price}}{\text{EPS}}",
        "guide":" - Less than 15 → Could be undervalued or troubled\n - Between 15-25 → Normal range for many sectors\n - Greater Than 25 → Growth stock or overvaluation"
    },
    'EPS (TTM)' : {
        'formal':"**Earnings Per Share (EPS)** represents a company's net profit divided by outstanding shares (TTM = last 12 months).",
        "casual":"This is your slice of the company’s pie. Bigger EPS? More pie!",
        "latex":r"\text{EPS} = \frac{\text{Net Income}}{\text{Shares Outstanding}}",
        "guide":"Compare EPS across years or with similar companies. Higher EPS generally signals better profitability."
    },
    "PEG Ratio" : {
        'formal': "**PEG Ratio** adjusts the P/E ratio for expected earnings growth.",
        "casual":"It tells you if you're paying too much for growth — think of it as a smarter P/E. Under 1? Could be a bargain.",
        "latex":r"\text{PEG Ratio} = \frac{\text{P/E Ratio}}{\text{EPS Growth Rate (\%)}}",
        "guide":"- Less than 1 → Could be undervalued\n- Between 1–2 → Fairly valued for many growth stocks\n- Greater than 2 → Possibly overvalued unless rapid growth continues \n\n if N\A then either data not available or Growth Rate is Negative so it'll be a Meaningless Quantity. You can verify this Below"
    },
    "P/B Ratio" : {
        'formal':"**P/B Ratio** compares the market price to the book value of the company.",
        "casual": "Basically: how much are you paying for every dollar of net assets? High P/B might mean high expectations — or hype.",
        "latex":r"\text{P/B Ratio} = \frac{\text{Market Price per Share}}{\text{Book Value per Share}}",
        "guide":"- Less than 1 → Possibly undervalued or distressed\n- Between 1–3 → Normal for many industries\n- Greater than 3 → Investors expect high returns or brand value"
    },
    "EV/FCF": {
        "formal": "**EV/FCF** compares a company's enterprise value to its free cash flow, giving a valuation multiple.",
        "casual": "How many times the company’s FCF you’re paying in EV.",
        "latex": r"\text{EV/FCF} = \frac{\text{Enterprise Value}}{\text{Free Cash Flow}}",
        "guide": "- Lower is better. < 15 is typically considered decent."
    },
    "FCF Yield": {
        "formal": "**FCF Yield** tells you what percentage of your investment is paid back in free cash flow.",
        "casual": "It’s like a yield — but from cold hard cash.",
        "latex": r"\text{FCF Yield} = \left(\frac{\text{FCF}}{\text{Market Cap}}\right) \times 100",
        "guide": "- Higher is better. > 5% is good."
    },
    "EV/EBITDA": {
        "formal": "**EV/EBITDA** shows how much you're paying for the company's earnings before interest, tax, depreciation, and amortization.",
        "casual": "Shows if the company is cheap or expensive based on operating earnings.",
        "latex": r"\text{EV/EBITDA} = \frac{\text{Enterprise Value}}{\text{EBITDA}}",
        "guide": "- < 10 is attractive. > 20 is expensive."
    },
    "Dividend Payout Ratio": {
        "formal": "**Dividend Payout Ratio** indicates how much of the net income is returned to shareholders as dividends.",
        "casual": "Shows how generous (or stingy) the company is with profits.",
        "latex": r"\text{Dividend Payout Ratio} = \left( \frac{\text{Total Dividends}}{\text{Net Income}} \right) \times 100",
        "guide": "- < 50% is sustainable. > 80% might be risky."
    },
}

RATIO_GROUPS = {
        "Profitability Ratios": [
            "Net Profit Margin", "Gross Margin", "Operating Margin", "Cash Flow Margin",
            "ROCE", "FCF Conversion"
        ],
        "Return Ratios": [
            "ROA", "ROE"
        ],
        "Liquidity Ratios": [
            "Current Ratio", "Quick Ratio", "Cash Ratio"
        ],
        "Solvency Ratios": [
            "Debt-to-Equity", "Debt Ratio", "Altman Z-Score", "Financial Leverage"
        ],
        "Efficiency Ratios": [
            "Inventory Turnover", "Asset Turnover", "Receivables Turnover", "CapEx Intensity"
        ]
    }

RATIO_EXPLANATIONS = {
    "Net Profit Margin": {
        "formal": "**Net Profit Margin** shows how much net income is generated as a percentage of revenue.",
        "casual": "What’s left after all bills — the real bottom-line percentage.",
        "latex": r"\text{Net Profit Margin} = \left( \frac{\text{Net Income}}{\text{Revenue}} \right) \times 100",
        "guide": "- >20% is excellent (depends on industry)\n- Negative? Uh-oh."
    },
    "Gross Margin": {
        "formal": "**Gross Margin** indicates how much profit a company makes after deducting the cost of goods sold.",
        "casual": "What’s left after making stuff but before paying anyone else.",
        "latex": r"\text{Gross Margin} = \left( \frac{\text{Gross Profit}}{\text{Revenue}} \right) \times 100",
        "guide": "- Higher margin = better pricing or efficiency.\n- Compare with peers in the same industry."
    },
    "Operating Margin": {
        "formal": "**Operating Margin** shows the percentage of revenue left after operating expenses.",
        "casual": "How much cash the core biz keeps after turning the lights on.",
        "latex": r"\text{Operating Margin} = \left( \frac{\text{Operating Income}}{\text{Revenue}} \right) \times 100",
        "guide": "- 15–25% is typical for strong companies.\n- Lower margins = efficiency issues."
    },
    "Cash Flow Margin": {
        "formal": "**Cash Flow Margin** measures operating cash flow as a percentage of revenue.",
        "casual": "How much real money comes in, not just accounting profits.",
        "latex": r"\text{CF Margin} = \left( \frac{\text{Operating Cash Flow}}{\text{Revenue}} \right) \times 100",
        "guide": "- >10% is strong.\n- Negative = red flag."
    },
    "ROCE": {
        "formal": "**Return on Capital Employed (ROCE)** shows how efficiently a company uses all capital to generate profit.",
        "casual": "How well the company makes money from the money it’s using.",
        "latex": r"\text{ROCE} = \frac{\text{Operating Income}}{\text{Capital Employed}}",
        "guide": "- >15% is excellent.\n- Must exceed cost of capital to create value."
    },
    "FCF Conversion": {
        "formal": "**Free Cash Flow Conversion** is the proportion of net income that turns into free cash flow.",
        "casual": "How much of those ‘profits’ turn into actual spendable cash.",
        "latex": r"\text{FCF Conversion} = \frac{\text{FCF}}{\text{Net Income}}",
        "guide": "- >80% is good.\n- <50% = profits might not be reliable."
    },
    "ROA": {
        "formal": "**Return on Assets (ROA)** tells how efficiently assets generate profit.",
        "casual": "Are your trucks and machines pulling their weight?",
        "latex": r"\text{ROA} = \frac{\text{Net Income}}{\text{Total Assets}}",
        "guide": "- 5–10% is decent.\n- Compare with industry."
    },
    "ROE": {
        "formal": "**Return on Equity (ROE)** shows how much profit shareholders earn on their equity.",
        "casual": "What the owners get back for their money in the biz.",
        "latex": r"\text{ROE} = \frac{\text{Net Income}}{\text{Shareholders' Equity}}",
        "guide": "- >15% is strong.\n- Compare across similar companies."
    },
    "Current Ratio": {
        "formal": "**Current Ratio** indicates short-term liquidity — can the company pay its bills?",
        "casual": "If everyone comes asking for money tomorrow, can the company survive?",
        "latex": r"\text{Current Ratio} = \frac{\text{Current Assets}}{\text{Current Liabilities}}",
        "guide": "- 1.5–2 is healthy.\n- <1 might mean cash problems."
    },
    "Quick Ratio": {
        "formal": "**Quick Ratio** is a stricter test of liquidity — excludes inventory.",
        "casual": "If it can’t sell stuff, can it still pay the bills?",
        "latex": r"\text{Quick Ratio} = \frac{\text{Current Assets} - \text{Inventory}}{\text{Current Liabilities}}",
        "guide": "- >1 is considered safe.\n- <1 is risky, especially in low-margin industries."
    },
    "Cash Ratio": {
        "formal": "**Cash Ratio** is the most conservative liquidity ratio — only cash & equivalents.",
        "casual": "Can it survive *right now* with only cash?",
        "latex": r"\text{Cash Ratio} = \frac{\text{Cash and Equivalents}}{\text{Current Liabilities}}",
        "guide": "- 0.5–1 is reasonable.\n- <0.2 = tight cash situation."
    },
    "Debt-to-Equity": {
        "formal": "**Debt-to-Equity Ratio** compares total liabilities to shareholders’ equity.",
        "casual": "How much of the biz is bank-owned vs owner-owned?",
        "latex": r"\text{Debt-to-Equity} = \frac{\text{Total Liabilities}}{\text{Equity}}",
        "guide": "- <1 is good.\n- >2 = heavy debt load."
    },
    "Debt Ratio": {
        "formal": "**Debt Ratio** shows total debt as a percentage of total assets.",
        "casual": "How much of the assets are borrowed?",
        "latex": r"\text{Debt Ratio} = \frac{\text{Total Liabilities}}{\text{Total Assets}}",
        "guide": "- <0.5 = good buffer.\n- >0.6 = may signal risk."
    },
    "Altman Z-Score": {
        "formal": "**Altman Z-Score** is a credit-risk model to predict bankruptcy probability.",
        "casual": "Fancy math to say: Will this company go bankrupt soon?",
        "latex": r"Z = 1.2A + 1.4B + 3.3C + 0.6D + 1.0E",
        "guide": "- Z > 3 = safe zone\n- 1.8 < Z < 3 = gray zone\n- Z < 1.8 = high risk"
    },
    "Inventory Turnover": {
        "formal": "**Inventory Turnover** measures how often inventory is sold and replaced.",
        "casual": "How fast they sell their stuff — or is it just collecting dust?",
        "latex": r"\text{Inventory Turnover} = \frac{\text{Revenue}}{\text{Inventory}}",
        "guide": "- High = efficient use of inventory.\n- Low = slow-moving or obsolete goods."
    },
    "Asset Turnover": {
        "formal": "**Asset Turnover** indicates how efficiently total assets generate revenue.",
        "casual": "How well is the company using what it owns to make money?",
        "latex": r"\text{Asset Turnover} = \frac{\text{Revenue}}{\text{Total Assets}}",
        "guide": "- >1 is strong (esp. for retail).\n- Low = underutilization."
    },
    "Receivables Turnover": {
        "formal": "**Receivables Turnover** shows how many times receivables are collected per period.",
        "casual": "How fast do customers actually *pay*?",
        "latex": r"\text{Receivables Turnover} = \frac{\text{Revenue}}{\text{Accounts Receivable}}",
        "guide": "- High = fast payments.\n- Low = credit or collection issues."
    },
    "CapEx Intensity": {
        "formal": "**CapEx Intensity** shows what portion of revenue is spent on capital investments.",
        "casual": "How much are they plowing back into buildings, tech, and stuff?",
        "latex": r"\text{CapEx Intensity} = \frac{\text{CapEx}}{\text{Revenue}}",
        "guide": "- High = expansion or asset-heavy model.\n- >15% can strain cash flow."
    }
}

HISTORICAL_CHART = {
    "formal":"The price at which the stock traded at.", 
    "casual":"The price you would have for the stock at that day",
    "guide":"Green Candle means Return was positie for that day. Red means it was negative. Dotted Blue Line indicates the day the report was published which is used in our calculations."
}

PIOTROSKI_METRICS = {
    "Net Income": {
        "formal": "**Net Income** is the company's total profit after all expenses and taxes.",
        "casual": "What’s left after all the bills — pure profit.",
        "latex": r"\text{Net Income} = \text{Revenue} - \text{Expenses} - \text{Taxes}",
        "guide": "Positive net income suggests profitability. A key signal of financial health."
    },
    "ROA": {
        "formal": "**Return on Assets (ROA)** measures how efficiently a company uses its assets to generate profit.",
        "casual": "How much bang you're getting for every buck of stuff the company owns.",
        "latex": r"\text{ROA} = \left( \frac{\text{Net Income}}{\text{Total Assets}} \right) \times 100",
        "guide": "ROA > 0 is considered healthy in Piotroski scoring."
    },
    "Operating Cash Flow": {
        "formal": "**Operating Cash Flow (OCF)** is the cash generated from a company’s core operations.",
        "casual": "Actual cash the business makes from its day job — not accounting tricks.",
        "latex": r"\text{OCF} = \text{Net Income} + \text{Non-cash Expenses} - \text{Changes in Working Capital}",
        "guide": "A positive OCF means the company’s business operations are bringing in cash."
    },
    "Operating Cash Flow > Net Income": {
        "formal": "This test checks if the company is generating more cash than accounting profit.",
        "casual": "If cash is higher than profit, it’s a sign the profits aren’t just on paper.",
        "latex": r"\text{Pass if: } \text{OCF} > \text{Net Income}",
        "guide": "Suggests earnings are backed by real cash — not just accruals."
    },
    "Lower Debt/Equity vs Last Year": {
        "formal": "This condition checks if the company's leverage (Debt/Equity) has decreased compared to the previous year.",
        "casual": "Is the company less in debt this year? That’s a good sign.",
        "latex": r"\text{D/E}_{t} < \text{D/E}_{t-1}",
        "guide": "A decline means reduced financial risk or better debt management."
    },
    "Higher Current Ratio vs Last Year": {
        "formal": "**Current Ratio** compares current assets to current liabilities. An increase suggests better short-term liquidity.",
        "casual": "Can they pay their bills more comfortably now than last year?",
        "latex": r"\text{Current Ratio} = \frac{\text{Current Assets}}{\text{Current Liabilities}}",
        "guide": "Higher ratio year-over-year suggests improved liquidity."
    },
    "New Shares Issued": {
        "formal": "This test checks whether the company issued new equity in the past year.",
        "casual": "If they didn’t dilute your shares, that’s a win.",
        "latex": r"\text{Fail if: } \text{Shares Outstanding}_{t} > \text{Shares Outstanding}_{t-1}",
        "guide": "Issuing new shares may signal distress or overvaluation. No issuance earns a Piotroski point."
    },
    "Higher Gross Margin vs Last Year": {
        "formal": "**Gross Margin** measures how much profit is retained from revenue after production costs.",
        "casual": "How fat is the profit before paying for marketing, admin, etc.?",
        "latex": r"\text{Gross Margin} = \left( \frac{\text{Gross Profit}}{\text{Revenue}} \right) \times 100",
        "guide": "Improving margin suggests better cost control or pricing power."
    },
    "Higher Asset Turnover vs Last Year": {
        "formal": "**Asset Turnover Ratio** measures how efficiently a company uses assets to generate sales.",
        "casual": "How much revenue they squeeze from each dollar of stuff they own.",
        "latex": r"\text{Asset Turnover} = \frac{\text{Revenue}}{\text{Total Assets}}",
        "guide": "An increase means the company is using its assets more efficiently."
    },
}

PIOTROSKI_EXPLANATION = {
    "formal": "**Piotroski F-Score** is a 0–9 scoring system that evaluates a company's financial strength based on profitability, leverage, liquidity, and operating efficiency. Each of 9 signals earns 1 point if criteria are met.",
    
    "casual": "Think of this as a report card for a company's financial health. The score goes from 0 (bad) to 9 (awesome). It's based on 9 signals like whether profits are up, debt is going down, or cash flow is solid.",

    "guide": """
**Interpretation Guide:**
- **8–9:** Strong fundamentals. Company passes nearly all quality checks.
- **6–7:** Decent score. Generally financially stable.
- **4–5:** Neutral zone. Investigate further.
- **0–3:** Weak fundamentals. Possible red flags.

**Scoring Criteria (1 point each):**
- **Profitability:**
  1. Net Income > 0\n
  2. ROA > 0\n
  3. Operating Cash Flow > 0\n
  4. CFO > Net Income\n

- **Leverage, Liquidity, and Funding:**
  5. Decrease in long-term debt\n
  6. Increase in current ratio\n
  7. No new equity issued\n

- **Operating Efficiency:**
  8. Higher gross margin vs. previous year\n
  9. Higher asset turnover vs. previous year\n

---

**⚠ Limitations in This Dashboard:**
- Our implementation **only includes criteria for which data is available via Yahoo Finance**.
- Metrics like **“New Equity Issued”** or **long-term debt comparisons** may be approximated or missing.
- Therefore, the final score may **differ slightly** from professional platforms like Bloomberg or GuruFocus.
"""
}

DUPONT_EXPLANATION = {
    "formal": "**DuPont Analysis** breaks down Return on Equity (ROE) into three components: profitability, efficiency, and leverage. This helps identify what’s driving or hurting a company’s returns.",
    
    "casual": "It’s like breaking ROE into parts to see where the profit really comes from — are they good at making money, using assets, or just taking on debt?",

    "latex": r"""
\begin{aligned}
\text{ROE} &= \text{Net Profit Margin} \times \text{Asset Turnover} \times \text{Equity Multiplier} \\[1em]
\text{Net Profit Margin} &= \frac{\text{Net Income}}{\text{Revenue}} \\[1em]
\text{Asset Turnover} &= \frac{\text{Revenue}}{\text{Total Assets}} \\[1em]
\text{Equity Multiplier} &= \frac{\text{Total Assets}}{\text{Equity}}
\end{aligned}
""",

    "guide": """
**Interpretation Guide:**
- **Net Profit Margin**: Measures profitability. Higher margin = more profit per dollar of sales.
- **Asset Turnover**: Shows efficiency. Higher = better use of assets to generate revenue.
- **Equity Multiplier**: Reflects leverage. High multiplier = more debt relative to equity.

**Reading the Result:**
- A high ROE from **strong margins and turnover** is a good sign.
- A high ROE driven by **leverage** (high equity multiplier) could be risky.
- Comparing components year-over-year can show if profitability is improving or just financial engineering.

---

**⚠ Limitations in This Dashboard:**
- Our DuPont implementation **depends on available Yahoo Finance data**, which may lack:
  - Consistent "Total Assets" or "Equity" values
  - Granular details like "Interest Burden" (for 5-step DuPont)
- We use the **3-step DuPont model** due to limited breakdowns.
- Treat this as a simplified ROE breakdown, not a full forensic tool.
"""
}

ABOUT_PAGE = """
Welcome to this **Financial Dashboard**, an educational tool designed to analyze public companies using real financial data.  
It offers both **insightful analysis** for investors and **guided explanations** for learners through **Dummy Mode**.

---

### 🔍 What This Project Does
- Retrieves real-time **financial statements** from Yahoo Finance (Income, Balance Sheet, Cash Flow)
- Computes over **30+ financial ratios and metrics**
- Presents **historical stock prices** with quarterly and yearly overlays
- Supports **interactive plotting** for visual trend analysis
- Offers advanced insights through:
    - 📊 **Piotroski F-Score**
    - 🧮 **DuPont Analysis**
    - 💡 **Valuation ratios** (PEG, EV/EBITDA, FCF Yield, P/B, etc.)

---

### 🧠 What is Dummy Mode?

When enabled, it transforms every metric card into an **interactive explanation module**.

Each metric comes with:
- 📘 **Formal definition**  
- 😄 **Casual description**  
- 🧮 **LaTeX-based formula**  
- 🔍 **Interpretation guide**

> ✅ Use Dummy Mode to understand *what a metric means*, *how it's calculated*, and *why it matters*.

**How to Enable:**
- Go to the **Sidebar** → Enable ✅ `Dummy Mode`

---

### 🛠 Key Features Overview

| Feature | Description |
|--------|-------------|
| 📈 **Metric Cards** | Key financial metrics with optional explanations |
| 📉 **Interactive Charts** | Stock price plots with earnings highlights |
| 🧠 **Dummy Mode** | Learn what every number means |
| 📊 **Grouped Tables** | Financials and ratios grouped by type (profitability, liquidity, etc.) |
| 📈 **Advanced Analysis** | Includes Piotroski F-Score and DuPont breakdown |
| 🧾 **Quarterly & Yearly Modes** | View short-term vs long-term trends |

---

### ⚠ Approximations & Data Limitations

This dashboard uses Yahoo Finance APIs, which means some limitations apply:

- **Missing Fields**: Yahoo Finance does not always provide:
    - Equity Issuance (used in Piotroski)
    - Some CapEx breakdowns
    - Interest Burden / Effective Tax Rate (for full DuPont)
- **Simplified Models**: Where full decomposition isn't possible, simplified formulas are used

📌 **These can cause differences** compared to platforms like Bloomberg, GuruFocus, or TIKR.

---

### 📢 Please Verify Before Using!

Do **not** make investment decisions without verifying metrics using reliable sources like:

- SEC EDGAR Filings
- Yahoo Finance (manually)
- Morningstar
- TIKR or Koyfin

The dashboard does not replace due diligence.

---

### 💾 Save Your Dashboard View (PDF Export)

You can save your dashboard as a PDF report by printing the page.

**To do this safely:**
1. Press **`Ctrl + P`** or open browser’s **Print → Save as PDF**
2. Before saving, ensure:
    - ✅ "Background graphics" is **enabled**
    - ✅ Zoom is set to **80%**
    - ✅ Layout is **Landscape**
    - ✅ Expand all desired explanation sections which you want in the final PDF

> 🔐 This avoids content getting cut off or omitted

---

### 🙌 Thank You!

This tool was built to **empower your financial analysis** and make learning metrics **easier and fun**.  
If you enjoy it or want to contribute new ideas, feel free to fork or expand this project!
    """